alias pik='git cherry-pick'
alias pikab='git cherry-pick --abort'
alias stat='git status'
alias cmt='git commit'
alias psh='git push'
alias ..='cd ..'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias codefire='ssh savoca@node2-c6100.codefi.re'
alias lk='ps -ef | grep'
alias wallpaper='feh --bg-scale'
alias chrome='google-chrome-stable'
alias tvdaemon='sudo systemctl start teamviewerd'
alias minecraft='java -jar ~/bin/Minecraft.jar'
alias wifi='nmcli dev wifi connect' #password

